name: Setup and Build Ziad-Portfolio

description: |
  This action sets up the environment and builds the Ziad-Portfolio project.

inputs:
  node-version:
    description: 'Version of Node.js to use for setting up the environment'
    required: true
    default: '16.x'

runs:
  using: 'node12'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main  # Adjust this to the branch you want to build from

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: ziad-portfolio-build
        path: ./build  # Change if your build directory is different
